### ISSUE TITLE
Retrieve data from FE gateway and show it in the PWA

### ISSUE THREAD

**Issue by mjcarsjens** [Gemeente-DenHaag/mijndenhaag-pwa#16]
In our Gatsby application we want to show data from the OpenZaak API.

For this issue we will simply show some data in our PWA which we retrieved from our Frontend Gateway.
For this we will need to have a BSN stored in our session, and do a GET request to our Frontend Gateway with the BSN as a request parameter. Now the Frontend Gateway should handle the rest and simply return the data from the OpenZaak API.

For this issue all that matters is retrieving any data from our Frontend Gateway and displaying it in some way. The specific representation of the data is handled in other issues.

**Comment by ogjtech** [comment]
@mjcarsjens what exactly is the goal of this story? To test whether the PWA can connect to and retrieve data from the gateway? That implies that any of the gateway endpoints must be fully implemented and tested, which none currently are. This story is inherently blocked and the gateway issues are currently too vague to be sufficiently implemented.
But, if the goal of this story is what I surmise, we may as well set up some Postman calls (as @bddjong is doing for the investigation into OpenZaak) that request the gateway and see if and what is returned. That would make this issue obsolete and saves us a lingering issue.

**Comment by bddjong** [comment]
Closed in favor of functional issues
