### ISSUE TITLE
Organizing the wiki

### ISSUE THREAD

**Issue by joostvanviegen** [Gemeente-DenHaag/mijndenhaag-pwa#24]
In order to document the information about OpenZaak we will need a wiki.

The wiki will need to be organized into different categories about the OpenZaak implementation. These categories are:
Guide on Implemented API's in the gateway and PWA.
Implementation guide on how to use the gateway in a project.
An overview of things needed to get started with the gateway and openzaak implementation.

Acceptation Criteria:

- [ ] Wiki created
- [ ] A section for a Guide on implemented API's: what has been implemented in the gateway?
- [ ] A section for a Guide on using the gateway to implement OpenZaak in a project
- [ ] A section for an overview of things needed to be able to use the OpenZaak gateway and the PWA

**Comment by bddjong** [comment]
I think this issue is obsolete? The gateway is no longer on the roadmap.
